version: '3'

services:
  # Database
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Quan@1999
      MYSQL_USER: quanlh
      MYSQL_PASSWORD: Quan@1999
    networks:
      - quanlh-network
    command: --sql_mode=""
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Quan@1999
    networks:
      - quanlh-network
networks:
  quanlh-network:
volumes:
  db_data: